platform :ios, "9.0"
use_frameworks!
inhibit_all_warnings!

workspace 'Bilibili.xcworkspace'

def pods
   
   #Frameworks
   pod 'RxSwift', '~> 4.0.0'
   pod 'RxCocoa', '~> 4.0.0'
   pod 'R.swift', '~> 4.0.0'
   pod 'SnapKit', '~> 4.0.0'
   pod 'Kingfisher', '~> 4.2.0'
   pod 'URLNavigator', '~> 2.0.0'
   pod 'SwiftyUserDefaults', '~>3.0.0'
   pod 'Hero', '~> 1.0.0'
   pod 'CryptoSwift', '~>0.7.2'
   pod 'SQLite.swift', '~> 0.11.4'
   pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift4'
   #pod 'GPUImage2', :podspec => './Bilibili/Podspec/GPUImage2.podspec'
   
   pod 'Sakura'
   
   #Frameworks - OC
   pod 'GPUImage', '~>0.1.7'
   pod 'lottie-ios', '~>1.0'
   pod 'MJRefresh', '~>3.1.0'
   pod 'WebViewJavascriptBridge', '~> 6.0.0'
   
   #Debug
   pod 'Reveal-SDK', '~> 4', :configurations => ['Debug']
   
   #Local
   pod 'BilibiliAPI', :path => './BilibiliAPI'

end

def react_native

  pod 'React', :subspecs => [
    'Core',
    'DevSupport',
    'BatchedBridge',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTActionSheet',
    'RCTImage',
    'RCTPushNotification',
    'RCTLinkingIOS',
    'RCTVibration',
  ], :path => '../node_modules/react-native'

  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

end

target :Bilibili do
    project 'Bilibili/Bilibili.xcodeproj'
    pods
    react_native

    target 'BilibiliTests' do
        inherit! :search_paths
    end
    
    target 'BilibiliUITests' do
        inherit! :search_paths
    end
end


#swift3pods = ['BilibiliAPI']
#
#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        if  swift3pods.include? target.name
#            target.build_configurations.each do |config|
#                config.build_settings['SWIFT_VERSION'] = '3.2'
#            end
#        end
#    end
#end

